application: ordinal-gear-93506
version: 1
runtime: php55
api_version: 1
threadsafe: false
instance_class: F1

automatic_scaling:
  min_idle_instances: 5
  max_idle_instances: 7
  min_pending_latency: 11ms
  max_pending_latency: 12ms


handlers:
- url: /main.php
  script: main.php

- url: /
  script: Register.php

- url: /delete.php
  script: /delete.php




- url: /upload_handler.php
  script: upload_handler.php